<?php

return [
	'SHOPIFY_API_KEY' => env('SHOPIFY_API_KEY'),
	'SHOPIFY_API_SECRET' => env('SHOPIFY_API_SECRET'),
	'SHOPIFY_SHOP_DOMAIN' => env('SHOPIFY_SHOP_DOMAIN'),
	'SHOPIFY_ACCESS_TOKEN' => env('SHOPIFY_ACCESS_TOKEN'),
];